<a href="https://colab.research.google.com/github/RexsyBima/pytorch_fundamental/blob/main/00_pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found



# Introduction to tensor

In [4]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
matrix.ndim

2

In [12]:
matrix[0], matrix[1], matrix[0][0]

(tensor([1, 2]), tensor([3, 4]), tensor(1))

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
 ### Random tensors
 #why?
 # many nn learn is that they start with tensors full of random numbers
 random_tensor = torch.rand(3,4)
 random_tensor

tensor([[0.9755, 0.0670, 0.2960, 0.1718],
        [0.5768, 0.3763, 0.6731, 0.5293],
        [0.6805, 0.8442, 0.0489, 0.8252]])

In [17]:
random_image_size_tensor = torch.rand(size=(3, 224,224)) #height, width, colour channels
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [18]:
# zeros and ones tensors
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(3,4)

In [21]:
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [26]:
 #range of tensor and tensor like

one_to_ten = torch.arange(0,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
# Tensor datatypes

#float32tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device="cpu", requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

# get information out of tensors

1. tensor not right datatype -> use `tensor.dtype`
2. tensor not right shape    -> use `tensor.shape`
3. tensor not right device   -> use `tensor.device`


In [34]:
#create a tensor

tensor_a = torch.rand(3,4)
tensor_a

tensor([[0.4959, 0.8295, 0.3189, 0.1107],
        [0.5474, 0.4112, 0.1869, 0.4207],
        [0.6773, 0.2250, 0.1039, 0.0605]])

In [38]:
print(f"dtype : {tensor_a.dtype}")
print(f"shape : {tensor_a.shape}")
print(f"device : {tensor_a.device}")


dtype : torch.float16
shape : torch.Size([3, 4])
device : cpu


In [37]:
 tensor_a = tensor_a.type(torch.float16)
 tensor_a.dtype

torch.float16